### ISSUE TITLE
What is dibdib?

### ISSUE THREAD

**Issue by H34dl3ss** [gxworks/dibdib#1]
Hi,
I have been browsing the f-droid repo and stumbled across the Dib2calc.
I'm trying to understand what "dibdib" stands for and what this special calculator is about.
I'm having a really hard time to figure it out!
Since I don't wanna die stupid, would you please elaborate on the "dibdib" term and how the tools are interconnected.
I'm sure you sacrificed a lot of time to create those tools and I think you should invest just a couple of minutes more
to explain the use case and benefit of your creation a little bit more in detail so people can decide if it fits their need.

Thank you!

**Comment by gxworks** [comment]
Thanks a lot! And sorry for having missed this issue.

DIB-DIB is what my very young daughter said when she watched me typing ('DIBBing') something on my palmtop many years ago :-)

For me it is a means of trying out various programming techniques, so initially it was not meant to be published. But some of my experiments ended up in something that can be partially useful for others, so I decided to put it on F-Droid.

Dib2Calc can be used as a 'not so nice' calculator (with a few nice features), for putting exotic characters ('Unicode') on the clipboard, and hopefully a few more things coming up. But it really lacks good documentation ... :-(

Cmp. https://github.com/gxworks/dibdib/blob/master/docs/apps/dib2calc.md for a few (too few) hints.

**Comment by gxworks** [comment]
I have added some more information under:

https://gitlab.com/dibdib/dib2calc
